// <auto-generated />
using System;
using BlogAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlogAPI.Infrastructure.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20250830111510_InitialCreateWithSeedData")]
    partial class InitialCreateWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlogAPI.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "CreatedAt");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Great introduction! Looking forward to more content.",
                            CreatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostId = 1,
                            UpdatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "Welcome to the community! This platform looks promising.",
                            CreatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostId = 1,
                            UpdatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Content = "ASP.NET Core is indeed powerful. Thanks for sharing your insights!",
                            CreatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostId = 2,
                            UpdatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Very helpful post! Could you write about Entity Framework next?",
                            CreatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostId = 2,
                            UpdatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Content = "Interesting perspective on the future of web development.",
                            CreatedAt = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostId = 3,
                            UpdatedAt = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = "AI integration is definitely game-changing. Excited to see where this goes!",
                            CreatedAt = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostId = 3,
                            UpdatedAt = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            Content = "Database design is often overlooked. Thanks for highlighting its importance!",
                            CreatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostId = 4,
                            UpdatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            Content = "Could you elaborate more on indexing strategies?",
                            CreatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostId = 4,
                            UpdatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Content = "Inspiring story! I'm just starting my coding journey too.",
                            CreatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostId = 5,
                            UpdatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            Content = "Great advice for beginners. Persistence is key!",
                            CreatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostId = 5,
                            UpdatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("BlogAPI.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Title");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is the first post in our blog system. Here you can share your thoughts, ideas, and experiences with the community. We're excited to see what amazing content you'll create!",
                            CreatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Welcome to Our Blog API",
                            UpdatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "ASP.NET Core is a powerful framework for building modern web applications. In this post, I'll share some tips and best practices that I've learned during my development journey.",
                            CreatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Getting Started with ASP.NET Core",
                            UpdatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Technology is constantly evolving, and web development is no exception. From AI integration to new frameworks, let's explore what the future holds for developers.",
                            CreatedAt = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "The Future of Web Development",
                            UpdatedAt = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Content = "Good database design is crucial for application performance. Here are some key principles: normalization, indexing, and choosing the right data types for your use case.",
                            CreatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Database Design Best Practices",
                            UpdatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Content = "Starting as a beginner can be overwhelming, but with persistence and practice, anyone can become a skilled developer. Here's my story and some advice for newcomers.",
                            CreatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "My Coding Journey",
                            UpdatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BlogAPI.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@blogapi.com",
                            PasswordHash = "admin123",
                            UpdatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john@example.com",
                            PasswordHash = "password123",
                            UpdatedAt = new DateTime(2024, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane@example.com",
                            PasswordHash = "password123",
                            UpdatedAt = new DateTime(2024, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Username = "janedoe"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "writer@blog.com",
                            PasswordHash = "writer123",
                            UpdatedAt = new DateTime(2024, 1, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            Username = "blogwriter"
                        });
                });

            modelBuilder.Entity("BlogAPI.Domain.Entities.Comment", b =>
                {
                    b.HasOne("BlogAPI.Domain.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogAPI.Domain.Entities.Post", b =>
                {
                    b.HasOne("BlogAPI.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
